### ISSUE TITLE
On Main Architecture [EPIC]

### ISSUE THREAD

**Issue by simonireilly** [simonireilly/natter#1]
# Architecture

I am implementing a Plugs and Adapters architecture for this project.

### Speech

Speech should be start-able and stop-able with the following API.

```javascript
start(onRecognitionCallback, speechContext={})
stop()
```

- [x] The onRecognitionCallback function will perform the parsing and execution of commands to the system.

```javascript
function onRecognitionCallback() {
  let commands = parser()
  executor(commands)
}

```

### Parser

A parser should be-able to receive one or more strings and parse them into a set of commands. The ideal object output is currently:

```javascript
[
  { 
    type: key/text,
    value: string,
    action: press/hold,
  }
]
```

This API may change as we implement more complex execution.

### Executor

The executor should process the object returned by the parser.

It would implement a method for sending keys (press/hold) and text (paste).

### Broadcaster

The broadcaster should implement send and receive between the UI and Main.
We should send small messages between the UI window and the Main window.
- [x] We should use these messages to retrieve `get/set` data in the store.
- [x] We should use these messages to `start/stop` services

### Store

- [x] We should use a basic store. I have implemented a simple one using an NPM library.

## UI

The React UI should process updates synchronously by sending them to the main thread store. 

e.g. Writing grammars should be done on that thread using the store 

### Pages

- [ ] Grammars
- [ ] Adapter Config
- [ ] Dashboard
