### ISSUE TITLE
Speech Adapters [EPIC]

### ISSUE THREAD

**Issue by simonireilly** [simonireilly/natter#2]
# Phase 1

- [x] Google speech API

# Phase 2

- [ ] Mozilla speech API
- [ ] AWS Transcribe API
- [ ] IBM Watson API  https://cloud.ibm.com/catalog/services/speech-to-text  
- [ ] Microsoft Azure Speech API https://azure.microsoft.com/en-us/services/cognitive-services/speech-services/ 

# Phase 3

- [ ] Native integration (iOS, Windows, Mozilla python binaries)
