### ISSUE TITLE
Parsing Adapters [EPIC]

### ISSUE THREAD

**Issue by simonireilly** [simonireilly/natter#3]
Some exploration of adapters for parsing revealed the following promising libraries:

# Phase 1

Parsing Libraries

- [ ] http://zaa.ch/jison/docs/#using-the-generated-parser
- [ ] https://pegjs.org
- [ ] https://nearley.js.org
- [ ] https://www.npmjs.com/package/simple-text-parser
